# Generated by Django 4.2.4 on 2024-06-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rating_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
